# Generated by Django 5.0.2 on 2024-03-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cartitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='name',
            field=models.CharField(default='null', max_length=233),
            preserve_default=False,
        ),
    ]
