# Generated by Django 5.0.2 on 2024-03-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=233),
        ),
    ]
